apiVersion: v1
kind: Service
metadata:
  name: {{ include "ans-docs.fullname" . }}
  labels:
    {{- include "ans-docs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ans-docs.selectorLabels" . | nindent 4 }}